# 0-indexed label for training, and corresponding labels
# Character(upper case) = A, I, U, E, O, ...., N (follow original characters) 
decoding_map = {
    0 : 'A',
    1 : 'I',
    2 : 'U',
    3 : 'E',
    4 : 'O',
    5 : 'KA',
    6 : 'KI',
    7 : 'KU',
    8 : 'KE',
    9 : 'KO',
    10 : 'SA',
    11 : 'SI',
    12 : 'SU',
    13 : 'SE',
    14 : 'SO',
    15 : 'TA',
    16 : 'TI',
    17 : 'TU',
    18 : 'TE',
    19 : 'TO',
    20 : 'NA',
    21 : 'NI',
    22 : 'NU',
    23 : 'NE',
    24 : 'NO',
    25 : 'HA',
    26 : 'HI',
    27 : 'HU',
    28 : 'HE',
    29 : 'HO',
    30 : 'MA',
    31 : 'MI',
    32 : 'MU',
    33 : 'ME',
    34 : 'MO',
    35 : 'YA',
    36 : 'YU',
    37 : 'YO',
    38 : 'RA',
    39 : 'RI',
    40 : 'RU',
    41 : 'RE',
    42 : 'RO',
    43 : 'WA',
    44 : 'WO',
    45 : 'N',
}

#revsersed direction for label to encodes. ex: encoding_map['N'] = 45
encoding_map = {v: k for k, v in decoding_map.items()} 